import type { AdminDistrictMetric } from './types';

export const mockAdminDistricts: AdminDistrictMetric[] = [
  {
    district: 'Pune',
    state: 'Maharashtra',
    eligiblePopulation: 1420000,
    applicationVolume: 894000,
    approvalRate: 88.4,
    utilizationRate: 78.2,
    unusedFundsCrores: 64.5,
    awarenessGapScore: 'Low',
    topMissingDocument: 'Hostel Non-Allotment Certificate',
  },
  {
    district: 'Gadchiroli',
    state: 'Maharashtra',
    eligiblePopulation: 640000,
    applicationVolume: 182000,
    approvalRate: 72.1,
    utilizationRate: 34.8,
    unusedFundsCrores: 118.2,
    awarenessGapScore: 'Severe',
    topMissingDocument: 'Income Certificate (Tehsildar)',
  },
  {
    district: 'Nandurbar',
    state: 'Maharashtra',
    eligiblePopulation: 780000,
    applicationVolume: 245000,
    approvalRate: 74.3,
    utilizationRate: 41.5,
    unusedFundsCrores: 92.4,
    awarenessGapScore: 'Severe',
    topMissingDocument: 'Caste Validity Certificate',
  },
  {
    district: 'Solapur',
    state: 'Maharashtra',
    eligiblePopulation: 1120000,
    applicationVolume: 670000,
    approvalRate: 82.5,
    utilizationRate: 64.9,
    unusedFundsCrores: 53.0,
    awarenessGapScore: 'Moderate',
    topMissingDocument: 'Aadhaar NPCI Bank Seeding',
  },
  {
    district: 'Nagpur',
    state: 'Maharashtra',
    eligiblePopulation: 1250000,
    applicationVolume: 820000,
    approvalRate: 86.8,
    utilizationRate: 74.6,
    unusedFundsCrores: 48.7,
    awarenessGapScore: 'Low',
    topMissingDocument: 'Rooftop Electricity Meter Bill',
  },
  {
    district: 'Nashik',
    state: 'Maharashtra',
    eligiblePopulation: 1310000,
    applicationVolume: 790000,
    approvalRate: 84.1,
    utilizationRate: 71.3,
    unusedFundsCrores: 59.2,
    awarenessGapScore: 'Low',
    topMissingDocument: '7/12 Land Record Mutation',
  },
  {
    district: 'Dharashiv (Osmanabad)',
    state: 'Maharashtra',
    eligiblePopulation: 580000,
    applicationVolume: 220000,
    approvalRate: 76.4,
    utilizationRate: 45.2,
    unusedFundsCrores: 61.8,
    awarenessGapScore: 'Severe',
    topMissingDocument: 'Income Certificate (Tehsildar)',
  },
];
