import type { Scheme } from './types';

export const mockSchemes: Scheme[] = [
  {
    id: 'maha-swadhar-2026',
    name: 'Dr. Babasaheb Ambedkar Swadhar Yojana',
    shortName: 'Swadhar Education Scheme',
    department: 'Social Justice and Special Assistance Department',
    ministry: 'Government of Maharashtra',
    level: 'State (Maharashtra)',
    category: 'Education & Scholarships',
    benefitAmount: '₹51,000 - ₹60,000',
    benefitType: 'Scholarship & Fee Waiver',
    benefitFrequency: 'Annual',
    matchScore: 94,
    matchStatus: 'Strong match',
    keyReason: 'Student residing away from home pursuing professional technical degree in Maharashtra with income under ₹2.5L.',
    targetAudience: 'SC/Navbudhha & reserved category collegiate students without government hostel allocation',
    deadline: '15 Nov 2026',
    officialPortal: 'mahadbt.maharashtra.gov.in',
    lastVerifiedDate: '24 Sep 2026',
    processingTime: '21 - 30 days',
    complexity: 'Low',
    maxIncomeLimit: 250000,
    minAge: 17,
    maxAge: 28,
    eligibleGenders: ['All', 'Female', 'Male', 'Transgender'],
    eligibleStates: ['Maharashtra'],
    summary: 'Direct financial assistance for food, accommodation, and educational material for backward category collegiate students not allotted government hostels.',
    eligibilityCriteria: [
      {
        id: 'c1',
        label: 'Domicile of Maharashtra',
        requirement: 'Must hold valid Maharashtra State Domicile Certificate',
        userStatus: 'Meets',
        explanation: 'Verified via uploaded Domicile certificate (Pune District).',
        ruleCode: 'MAHA-DOM-SEC3',
      },
      {
        id: 'c2',
        label: 'Family Annual Income Limit',
        requirement: 'Gross annual parental income must be ≤ ₹2,50,000',
        userStatus: 'Meets',
        explanation: 'Your verified family income is ₹2,10,000, which satisfies the limit.',
        ruleCode: 'INC-L25-REV',
      },
      {
        id: 'c3',
        label: 'Current Academic Enrollment',
        requirement: 'Enrolled in recognized higher diploma or degree program',
        userStatus: 'Meets',
        explanation: 'College bona fide and 2nd year mark sheet extracted.',
        ruleCode: 'EDU-HE-ENR',
      },
      {
        id: 'c4',
        label: 'Hostel Non-Allotment Certificate',
        requirement: 'Declaration that student did not receive government hostel room',
        userStatus: 'Requires Document',
        explanation: 'Self-undertaking format needs to be signed and attached.',
        ruleCode: 'SWD-HST-DECL',
      },
      {
        id: 'c5',
        label: 'Bank Account Aadhaar Seeding',
        requirement: 'Aadhaar-seeded NPCI mapper active bank account',
        userStatus: 'Meets',
        explanation: 'Bank of Maharashtra account is NPCI mapped.',
        ruleCode: 'DBT-NPCI-01',
      },
    ],
    documents: [
      { id: 'd1', name: 'Aadhaar Card', isAvailable: true, status: 'verified', extractedValue: 'XXXX-XXXX-4921' },
      { id: 'd2', name: 'Maharashtra Domicile Certificate', isAvailable: true, status: 'verified', extractedValue: 'DOM/2023/MH/49102' },
      { id: 'd3', name: 'Income Certificate (Tehsildar)', isAvailable: true, status: 'needs_review', extractedValue: '₹2,10,000', notes: 'Slight blur on issue seal' },
      { id: 'd4', name: 'Caste Certificate / Validity', isAvailable: true, status: 'verified', extractedValue: 'CST/PUN/88219' },
      { id: 'd5', name: 'College Admission Bona Fide', isAvailable: true, status: 'verified', extractedValue: 'COEP Tech / Enr 2023-44' },
      { id: 'd6', name: 'Hostel Non-Allotment Undertaking', isAvailable: false, status: 'missing', notes: 'Download format from YojanaSetu Copilot' },
    ],
    applicationSteps: [
      'Document Pre-check & Digilocker Import',
      'Eligibility Verification & Institute Tagging',
      'Address & Distance Declaration Form',
      'Hostel Non-Availability Undertaking Upload',
      'Aadhaar e-Sign & Final Submission',
      'Application Tracking on MahaDBT Gateway',
    ],
  },
  {
    id: 'post-matric-scholarship-2026',
    name: 'Centrally Sponsored Post-Matric Scholarship',
    shortName: 'Post-Matric National Scholarship',
    department: 'Department of Higher Education',
    ministry: 'Ministry of Education & Social Justice',
    level: 'Central',
    category: 'Education & Scholarships',
    benefitAmount: 'Up to ₹50,000/year',
    benefitType: 'Scholarship & Fee Waiver',
    benefitFrequency: 'Annual',
    matchScore: 91,
    matchStatus: 'Strong match',
    keyReason: 'Meets age criteria, pursuing accredited higher education degree, verified reserved category background.',
    targetAudience: 'Eligible students studying post-secondary courses with household income under ₹2.5 Lakhs.',
    deadline: '30 Oct 2026',
    officialPortal: 'scholarships.gov.in',
    lastVerifiedDate: '21 Sep 2026',
    processingTime: '30 - 45 days',
    complexity: 'Medium',
    maxIncomeLimit: 250000,
    minAge: 16,
    maxAge: 30,
    eligibleGenders: ['All', 'Female', 'Male', 'Transgender'],
    eligibleStates: ['All India'],
    summary: 'Comprehensive financial assistance covering tuition reimbursement and monthly maintenance allowances for students pursuing graduation and diploma studies.',
    eligibilityCriteria: [
      {
        id: 'pms1',
        label: 'Academic Qualification',
        requirement: 'Minimum 50% aggregate in 12th / Previous Semester',
        userStatus: 'Meets',
        explanation: 'Previous semester aggregate: 71.4% extracted from transcript.',
      },
      {
        id: 'pms2',
        label: 'Income Cap (Family)',
        requirement: 'Under ₹2,50,000 per annum from all verifiable sources',
        userStatus: 'Meets',
        explanation: 'Declared & verified income: ₹2,10,000 meets criteria.',
      },
      {
        id: 'pms3',
        label: 'Category Affirmation',
        requirement: 'Recognized SC/ST/OBC category certificate',
        userStatus: 'Meets',
        explanation: 'OBC status verified via state certificate registry.',
      },
    ],
    documents: [
      { id: 'p1', name: 'Aadhaar Card', isAvailable: true, status: 'verified' },
      { id: 'p2', name: 'Income Certificate', isAvailable: true, status: 'needs_review' },
      { id: 'p3', name: 'Caste Certificate', isAvailable: true, status: 'verified' },
      { id: 'p4', name: 'Previous Year Marksheet', isAvailable: true, status: 'verified' },
      { id: 'p5', name: 'Bank Passbook / Cancelled Cheque', isAvailable: true, status: 'verified' },
      { id: 'p6', name: 'Current Fee Receipt', isAvailable: false, status: 'missing' },
    ],
    applicationSteps: [
      'National Scholarship Portal (NSP) OTR registration',
      'Scheme selection & Institute verification',
      'Upload academic records & Fee receipt',
      'Aadhaar OTP authentication',
      'College Nodal Officer Approval',
      'State DBT Disbursal',
    ],
  },
  {
    id: 'pm-kisan-samman-2026',
    name: 'PM Kisan Samman Nidhi (Farmer Support)',
    shortName: 'PM-KISAN',
    department: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture',
    level: 'Central',
    category: 'Agriculture & Farmers',
    benefitAmount: '₹6,000 / year',
    benefitType: 'Direct Benefit Transfer',
    benefitFrequency: 'Quarterly',
    matchScore: 88,
    matchStatus: 'Strong match',
    keyReason: 'Household holds 1.8 acres cultivable farmland with active Aadhaar land title link.',
    targetAudience: 'Small and marginal landholder farmer families with cultivable land.',
    deadline: 'Rolling (Continuous)',
    officialPortal: 'pmkisan.gov.in',
    lastVerifiedDate: '26 Sep 2026',
    processingTime: '15 - 20 days',
    complexity: 'Low',
    maxIncomeLimit: 500000,
    minAge: 18,
    maxAge: 75,
    eligibleGenders: ['All', 'Female', 'Male'],
    eligibleStates: ['All India'],
    summary: 'Direct income support of ₹6,000 per year transferred in three equal installments of ₹2,000 each directly into the bank accounts of landholding farmer families.',
    eligibilityCriteria: [
      {
        id: 'k1',
        label: 'Cultivable Land Record',
        requirement: 'Must own cultivable agricultural land in family name',
        userStatus: 'Meets',
        explanation: 'Maharashtra Bhulekh 7/12 record extracted: 1.8 acres in Haveli.',
      },
      {
        id: 'k2',
        label: 'Aadhaar eKYC Completion',
        requirement: 'Mandatory Aadhaar biometric or OTP eKYC verification',
        userStatus: 'Meets',
        explanation: 'eKYC verified on 12 June 2026.',
      },
      {
        id: 'k3',
        label: 'Income Tax Exclusion Check',
        requirement: 'Applicant must not be an assessed income-tax payer',
        userStatus: 'Meets',
        explanation: 'No IT return filing under PAN.',
      },
    ],
    documents: [
      { id: 'k1', name: 'Aadhaar Card', isAvailable: true, status: 'verified' },
      { id: 'k2', name: 'Land Record (7/12 Extract)', isAvailable: true, status: 'verified' },
      { id: 'k3', name: 'Aadhaar-linked Bank Account', isAvailable: true, status: 'verified' },
    ],
    applicationSteps: [
      'Self-registration via PM Kisan Portal / CSC',
      'Enter Aadhaar & State Land Ledger Code',
      'OTP validation & Family Member Declaration',
      'District Revenue Officer land-title verification',
      'Installment activation on PFMS',
    ],
  },
  {
    id: 'maha-youth-stipend-borderline',
    name: 'Chhatrapati Shahu Maharaj Shikshan Shulk Fellowship',
    shortName: 'Higher Education Fee Reimbursement',
    department: 'Higher and Technical Education Department',
    ministry: 'Government of Maharashtra',
    level: 'State (Maharashtra)',
    category: 'Education & Scholarships',
    benefitAmount: '50% - 100% Tuition Fee Waiver',
    benefitType: 'Scholarship & Fee Waiver',
    benefitFrequency: 'Per Semester',
    matchScore: 68,
    matchStatus: 'Borderline',
    keyReason: 'Your declared annual income is ₹2,10,000, whereas the simplified automatic slab is ₹2,00,000. Full waiver requires verification of agricultural gross receipts.',
    targetAudience: 'Economically weaker and backwards classes admitted through CAP round in professional courses.',
    deadline: '20 Nov 2026',
    officialPortal: 'mahadbt.maharashtra.gov.in',
    lastVerifiedDate: '19 Sep 2026',
    processingTime: '30 days',
    complexity: 'Medium',
    maxIncomeLimit: 200000, // Borderline trigger!
    minAge: 17,
    maxAge: 32,
    eligibleGenders: ['All', 'Female', 'Male'],
    eligibleStates: ['Maharashtra'],
    summary: 'Provides 50% tuition and exam fee reimbursement for students admitted through centralized admissions with family income up to ₹8,00,000, with 100% bracket at ₹2,00,000.',
    eligibilityCriteria: [
      {
        id: 'b1',
        label: 'Income Threshold Classification',
        requirement: 'Automatic Tier-1 full waiver: ≤ ₹2,00,000. Tier-2 50% waiver: ₹2,00,001 - ₹8,00,000.',
        userStatus: 'Borderline',
        explanation: 'Your declared income is ₹2,10,000 (₹10,000 above the Tier 1 ceiling). Eligible for Tier 2 (50% fee waiver) or Tier 1 upon agricultural deduction proof.',
        ruleCode: 'MHA-FEES-SLAB2',
      },
      {
        id: 'b2',
        label: 'CAP Round Admission Confirmation',
        requirement: 'Must have secured seat through State Centralized Allotment Process',
        userStatus: 'Meets',
        explanation: 'CAP allotment letter verified.',
      },
      {
        id: 'b3',
        label: 'Attendance & Backlog Rule',
        requirement: 'Minimum 75% attendance and no more than 2 allowed backlogs',
        userStatus: 'Meets',
        explanation: 'Current semester attendance is 84%.',
      },
    ],
    documents: [
      { id: 'bdoc1', name: 'CAP Allotment Letter', isAvailable: true, status: 'verified' },
      { id: 'bdoc2', name: 'Tehsildar Income Certificate', isAvailable: true, status: 'needs_review', notes: 'Income stated as ₹2,10,000' },
      { id: 'bdoc3', name: 'Ration Card / Family Declaration', isAvailable: false, status: 'missing' },
    ],
    applicationSteps: [
      'Select CAP allotment ID on MahaDBT',
      'Clarify Income Tier (Tier 2 50% fee or request Agricultural deduction)',
      'Upload Tehsildar Income Certificate and Ration Card',
      'Submit to College Verification Officer',
      'Fee adjusted directly in college treasury',
    ],
  },
  {
    id: 'pm-surya-ghar-2026',
    name: 'PM Surya Ghar: Muft Bijli Yojana (Rooftop Solar)',
    shortName: 'PM Surya Ghar Solar Subsidy',
    department: 'Ministry of New and Renewable Energy',
    ministry: 'Central Government of India',
    level: 'Central',
    category: 'Housing & Shelter',
    benefitAmount: '₹30,000 - ₹78,000 Direct Subsidy',
    benefitType: 'Subsidy & Grant',
    benefitFrequency: 'One-time',
    matchScore: 78,
    matchStatus: 'Potential match',
    keyReason: 'Household owns rural independent residential roof with domestic electricity connection.',
    targetAudience: 'Residential households seeking rooftop solar installation up to 3 kW capacity.',
    deadline: 'Rolling Scheme',
    officialPortal: 'pmsuryaghar.gov.in',
    lastVerifiedDate: '15 Sep 2026',
    processingTime: '25 - 35 days',
    complexity: 'Medium',
    maxIncomeLimit: 1200000,
    minAge: 18,
    maxAge: 80,
    eligibleGenders: ['All'],
    eligibleStates: ['All India'],
    summary: 'Provides direct financial subsidy for installing rooftop solar panels, providing up to 300 units of free electricity every month for residential households.',
    eligibilityCriteria: [
      {
        id: 'sg1',
        label: 'Residential Electricity Meter',
        requirement: 'Active domestic low-tension electricity consumer connection',
        userStatus: 'Meets',
        explanation: 'MSEDCL electricity bill verified.',
      },
      {
        id: 'sg2',
        label: 'Roof Ownership Rights',
        requirement: 'Unobstructed roof space or terrace with legal ownership',
        userStatus: 'Meets',
        explanation: 'Village Gram Panchayat property registration confirmed.',
      },
    ],
    documents: [
      { id: 'sgdoc1', name: 'Latest Electricity Bill (Past 3 Months)', isAvailable: true, status: 'verified' },
      { id: 'sgdoc2', name: 'Roof Ownership / Property Tax Receipt', isAvailable: true, status: 'verified' },
      { id: 'sgdoc3', name: 'Aadhaar Card', isAvailable: true, status: 'verified' },
    ],
    applicationSteps: [
      'Register on National Portal with DISCOM consumer number',
      'Receive technical feasibility approval from MSEDCL',
      'Select registered empanelled vendor for installation',
      'Net-metering inspection and commissioning certificate',
      'Subsidy credited directly into bank account in 30 days',
    ],
  },
  {
    id: 'pm-mudra-yojana-2026',
    name: 'Pradhan Mantri MUDRA Yojana (Kishor / Tarun Loan)',
    shortName: 'PMMY Business Loan Support',
    department: 'Department of Financial Services',
    ministry: 'Ministry of Finance',
    level: 'Central',
    category: 'Micro & Small Business',
    benefitAmount: 'Up to ₹10,00,000 Collateral-Free Credit',
    benefitType: 'Credit / Loan Support',
    benefitFrequency: 'One-time',
    matchScore: 72,
    matchStatus: 'Potential match',
    keyReason: 'Applicable if expanding rural agri-service, workshop or food processing enterprise.',
    targetAudience: 'Non-corporate, non-farm small/micro enterprises and startups.',
    deadline: 'Continuous',
    officialPortal: 'mudra.org.in',
    lastVerifiedDate: '10 Sep 2026',
    processingTime: '14 - 21 days',
    complexity: 'High',
    maxIncomeLimit: 2500000,
    minAge: 18,
    maxAge: 65,
    eligibleGenders: ['All'],
    eligibleStates: ['All India'],
    summary: 'Collateral-free institutional credit up to ₹10 Lakhs (extended up to ₹20 Lakhs under Tarun Plus) for non-corporate micro enterprises at subsidized interest rates.',
    eligibilityCriteria: [
      {
        id: 'md1',
        label: 'Viable Business Proposal',
        requirement: 'Project report or plan for proposed micro-enterprise',
        userStatus: 'Requires Document',
        explanation: 'Need simple business outline or quotation for equipment purchase.',
      },
      {
        id: 'md2',
        label: 'No Defaulter Status',
        requirement: 'Applicant should not have defaulted with any scheduled commercial bank',
        userStatus: 'Meets',
        explanation: 'CIBIL score check passes benchmark (742).',
      },
    ],
    documents: [
      { id: 'm1', name: 'Aadhaar & PAN Card', isAvailable: true, status: 'verified' },
      { id: 'm2', name: 'Udyam Registration Certificate', isAvailable: false, status: 'missing' },
      { id: 'm3', name: 'Bank Statement (Last 6 Months)', isAvailable: true, status: 'verified' },
    ],
    applicationSteps: [
      'Prepare project estimation or asset quote',
      'Submit Udyam registration online',
      'Apply via JanSamarth portal or partner bank branch',
      'Field verification by Branch Officer',
      'Loan sanction & Mudra Debit Card dispatch',
    ],
  },
];
