import type { UserDocument } from './types';

export const mockUserDocuments: UserDocument[] = [
  {
    id: 'doc-aadhaar',
    name: 'Aadhaar Identity Card',
    category: 'Identity',
    fileName: 'aadhaar_card_rahul_patil.pdf',
    fileSize: '1.2 MB',
    uploadedAt: '14 Aug 2026, 11:20 AM',
    source: 'DigiLocker',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: true,
      digitalSignatureValid: true,
      details: [
        'UIDAI Cryptographic QR signature verified with SHA-256 digest',
        'Direct DigiLocker API hash matched government central repository',
        'Facial portrait conforms to ISO/IEC 19794-5 specifications',
      ],
    },
    extractedFields: [
      { field: 'Full Name', extractedValue: 'Rahul Sambhaji Patil', userValue: 'Rahul S. Patil', confidence: 0.99, match: true },
      { field: 'Date of Birth', extractedValue: '14/04/2005', userValue: '2005-04-14', confidence: 0.98, match: true },
      { field: 'Gender', extractedValue: 'Male', userValue: 'Male', confidence: 1.0, match: true },
      { field: 'Aadhaar Number', extractedValue: 'XXXX-XXXX-4921', userValue: 'XXXX-XXXX-4921', confidence: 0.99, match: true },
      { field: 'Residential Address', extractedValue: 'Plot 42, Haveli, Wagholi, Pune 412207, Maharashtra', userValue: 'Pune, Maharashtra', confidence: 0.94, match: true },
    ],
  },
  {
    id: 'doc-income',
    name: 'Income Certificate (Tehsildar)',
    category: 'Income',
    fileName: 'income_certificate_2025_26.jpg',
    fileSize: '840 KB',
    uploadedAt: '12 Sep 2026, 04:45 PM',
    source: 'Upload',
    ocrStatus: 'complete',
    qualityStatus: 'quality_issue',
    verificationStatus: 'Needs Review',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: true, // Edge blur indicator
      issuingAuthorityVerified: false,
      digitalSignatureValid: false,
      details: [
        'Document layout conforms to Maharashtra Revenue Department standard format',
        'Potential compression artifacts or mild lens glare near Tehsildar rubber seal area',
        'Bar code extracted with 78% clarity; manual check recommended',
        'Issuing authority online verification pending portal response',
      ],
    },
    extractedFields: [
      { field: 'Head of Family', extractedValue: 'Sambhaji Tukaram Patil', userValue: 'Sambhaji Patil', confidence: 0.91, match: true },
      { field: 'Annual Income', extractedValue: '₹2,10,000', userValue: '₹2,10,000', confidence: 0.88, match: true },
      { field: 'Certificate Barcode', extractedValue: 'MH-REV-2025-884129', userValue: 'MH-REV-2025-884129', confidence: 0.82, match: true },
      { field: 'Date of Issue', extractedValue: '18/06/2025', userValue: '2025-06-18', confidence: 0.89, match: true },
      { field: 'Issuing Officer', extractedValue: 'Tehsildar Office, Haveli Pune', userValue: 'Tehsildar Haveli', confidence: 0.86, match: true },
    ],
  },
  {
    id: 'doc-caste',
    name: 'OBC Caste Certificate',
    category: 'Caste / Category',
    fileName: 'caste_certificate_patil.pdf',
    fileSize: '2.1 MB',
    uploadedAt: '10 Aug 2026, 02:15 PM',
    source: 'DigiLocker',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: true,
      digitalSignatureValid: true,
      details: [
        'Issued by Sub-Divisional Officer Pune Division',
        'Authentic digital DSC seal registered on MahaOnline system',
        'Caste serial matches Central & State Other Backward Classes gazette',
      ],
    },
    extractedFields: [
      { field: 'Candidate Name', extractedValue: 'Rahul Sambhaji Patil', userValue: 'Rahul S. Patil', confidence: 0.99, match: true },
      { field: 'Category', extractedValue: 'OBC (Other Backward Class)', userValue: 'OBC', confidence: 0.99, match: true },
      { field: 'Certificate Number', extractedValue: 'SDO/PUN/2022/99104', userValue: 'SDO/PUN/2022/99104', confidence: 0.97, match: true },
    ],
  },
  {
    id: 'doc-domicile',
    name: 'Maharashtra State Domicile',
    category: 'Residence',
    fileName: 'domicile_certificate.pdf',
    fileSize: '1.5 MB',
    uploadedAt: '10 Aug 2026, 02:20 PM',
    source: 'DigiLocker',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: true,
      digitalSignatureValid: true,
      details: ['Valid Domicile certification verified on DigiLocker vault.'],
    },
    extractedFields: [
      { field: 'Certificate Holder', extractedValue: 'Rahul Sambhaji Patil', userValue: 'Rahul S. Patil', confidence: 0.98, match: true },
      { field: 'Domicile State', extractedValue: 'Maharashtra', userValue: 'Maharashtra', confidence: 1.0, match: true },
    ],
  },
  {
    id: 'doc-marksheet',
    name: 'Diploma / Degree Mark Sheet (Sem 4)',
    category: 'Education',
    fileName: 'sem4_marksheet_coep.pdf',
    fileSize: '3.4 MB',
    uploadedAt: '18 Aug 2026, 10:05 AM',
    source: 'Upload',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: true,
      digitalSignatureValid: false,
      details: ['University Controller of Examinations watermarked layout recognized.'],
    },
    extractedFields: [
      { field: 'Candidate Name', extractedValue: 'Rahul S. Patil', userValue: 'Rahul S. Patil', confidence: 0.96, match: true },
      { field: 'CGPA / Percentage', extractedValue: '7.82 CGPA (71.4%)', userValue: '71.4%', confidence: 0.94, match: true },
      { field: 'Academic Status', extractedValue: 'First Class with Distinction', userValue: 'Passed', confidence: 0.92, match: true },
    ],
  },
  {
    id: 'doc-bank',
    name: 'Bank Passbook Front Page (NPCI Seeded)',
    category: 'Banking',
    fileName: 'bank_of_maharashtra_passbook.png',
    fileSize: '920 KB',
    uploadedAt: '22 Aug 2026, 03:30 PM',
    source: 'Upload',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: true,
      digitalSignatureValid: false,
      details: ['IFSC code verified against Reserve Bank of India database.'],
    },
    extractedFields: [
      { field: 'Account Holder', extractedValue: 'Rahul Sambhaji Patil', userValue: 'Rahul S. Patil', confidence: 0.97, match: true },
      { field: 'Account Number', extractedValue: '60199482910', userValue: '60199482910', confidence: 0.99, match: true },
      { field: 'IFSC Code', extractedValue: 'MAHB0000412', userValue: 'MAHB0000412', confidence: 0.99, match: true },
      { field: 'Branch', extractedValue: 'Wagholi Branch, Pune', userValue: 'Pune Wagholi', confidence: 0.93, match: true },
    ],
  },
  {
    id: 'doc-land',
    name: '7/12 Land Ledger Extract (Bhulekh)',
    category: 'Land / Property',
    fileName: 'bhulekh_7_12_extract.pdf',
    fileSize: '1.8 MB',
    uploadedAt: '25 Aug 2026, 09:12 AM',
    source: 'DigiLocker',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: true,
      digitalSignatureValid: true,
      details: ['Digitally signed Mahabhulekh certified extract with QR verification code.'],
    },
    extractedFields: [
      { field: 'Survey / Gut Number', extractedValue: 'Gut No. 142/2A', userValue: 'Gut No. 142', confidence: 0.96, match: true },
      { field: 'Land Area (Hectares)', extractedValue: '0.73 Hectares (1.80 Acres)', userValue: '1.8 Acres', confidence: 0.98, match: true },
      { field: 'Cultivation Category', extractedValue: 'Jirayat (Dry Land Farming)', userValue: 'Agricultural', confidence: 0.91, match: true },
    ],
  },
  {
    id: 'doc-ration',
    name: 'Family Ration Card',
    category: 'Residence',
    fileName: 'family_ration_card_pune.jpg',
    fileSize: '1.1 MB',
    uploadedAt: '05 Sep 2026, 12:40 PM',
    source: 'Upload',
    ocrStatus: 'complete',
    qualityStatus: 'readable',
    verificationStatus: 'Verified',
    authenticitySignals: {
      structureRecognized: true,
      ocrConsistencyPassed: true,
      imageManipulationDetected: false,
      issuingAuthorityVerified: false,
      digitalSignatureValid: false,
      details: ['Ration card booklet scan verified. 5 family members listed.'],
    },
    extractedFields: [
      { field: 'Card Type', extractedValue: 'Orange (Non-Priority Household APL)', userValue: 'Orange Card', confidence: 0.92, match: true },
      { field: 'Total Members', extractedValue: '5 Persons', userValue: '5', confidence: 0.95, match: true },
    ],
  },
];
