import type { ApplicationRecord } from './types';

export const mockApplications: ApplicationRecord[] = [
  {
    id: 'app-001',
    applicationNumber: 'APP-2026-MH-94182',
    schemeId: 'maha-swadhar-2026',
    schemeName: 'Dr. Babasaheb Ambedkar Swadhar Yojana',
    department: 'Social Justice and Special Assistance Department',
    benefitAmount: '₹51,000 / year',
    submittedDate: '14 Sep 2026',
    lastUpdated: '26 Sep 2026',
    currentStatus: 'Department Review',
    currentStepIndex: 3,
    totalSteps: 5,
    expectedNextStep: 'District Social Welfare Officer desk approval scheduled within 4 business days',
    timeline: [
      { stage: 'Application Submitted', date: '14 Sep 2026', status: 'completed', note: 'Online dossier filed via YojanaSetu MahaDBT connector' },
      { stage: 'Documents Verified by AI Engine', date: '15 Sep 2026', status: 'completed', note: 'Aadhaar, Domicile, and College bona fide verified' },
      { stage: 'College Nodal Desk Verification', date: '21 Sep 2026', status: 'completed', note: 'COEP Nodal Officer verified continuous student attendance' },
      { stage: 'Department Review (Social Welfare Pune)', date: '25 Sep 2026', status: 'current', note: 'Scrutiny of residential distance and rent declaration' },
      { stage: 'DBT Fund Disbursal', date: 'Pending', status: 'pending', note: 'Direct credit to Bank of Maharashtra A/C' },
    ],
  },
  {
    id: 'app-002',
    applicationNumber: 'APP-2026-NSP-77102',
    schemeId: 'post-matric-scholarship-2026',
    schemeName: 'Centrally Sponsored Post-Matric Scholarship',
    department: 'Department of Higher Education',
    benefitAmount: '₹38,000 / year',
    submittedDate: '02 Sep 2026',
    lastUpdated: '24 Sep 2026',
    currentStatus: 'Action Required',
    currentStepIndex: 2,
    totalSteps: 5,
    expectedNextStep: 'Applicant must replace blurry Income Certificate with readable PDF/Tehsildar copy',
    actionRequiredMessage: 'The uploaded Income Certificate contains blur around the official Tehsildar seal. Please replace it within 7 days to prevent application rejection.',
    actionRequiredType: 'replace_document',
    timeline: [
      { stage: 'Application Submitted', date: '02 Sep 2026', status: 'completed', note: 'NSP reference generated #NSP/2026/89410' },
      { stage: 'Document Validation', date: '12 Sep 2026', status: 'warning', note: 'Income certificate flagged: blur detected around issue seal' },
      { stage: 'Institute Verification', date: '19 Sep 2026', status: 'completed', note: 'College endorsed applicant bonafide' },
      { stage: 'State Scrutiny', date: 'Pending', status: 'pending', note: 'On hold awaiting clear income proof' },
      { stage: 'PFMS Sanction', date: 'Pending', status: 'pending', note: 'Scholarship credit pending' },
    ],
  },
  {
    id: 'app-003',
    applicationNumber: 'APP-2025-AGR-40192',
    schemeId: 'pm-kisan-samman-2026',
    schemeName: 'PM Kisan Samman Nidhi',
    department: 'Ministry of Agriculture and Farmers Welfare',
    benefitAmount: '₹6,000 / year',
    submittedDate: '10 Feb 2026',
    lastUpdated: '22 Aug 2026',
    currentStatus: 'Disbursed',
    currentStepIndex: 5,
    totalSteps: 5,
    expectedNextStep: 'Next installment (18th Kist) scheduled for credit in November 2026',
    timeline: [
      { stage: 'Self Registration Completed', date: '10 Feb 2026', status: 'completed', note: 'eKYC & 7/12 Land title linked' },
      { stage: 'District Revenue Verification', date: '28 Feb 2026', status: 'completed', note: 'Patwari & Tehsildar validated land ownership' },
      { stage: 'State Nodal Desk Approval', date: '15 Mar 2026', status: 'completed', note: 'Maharashtra Agriculture Dept approved' },
      { stage: 'PFMS Account Validation', date: '20 Mar 2026', status: 'completed', note: 'NPCI bank account linked successfully' },
      { stage: '17th Installment Disbursed', date: '22 Aug 2026', status: 'completed', note: '₹2,000 credited to Bank of Maharashtra A/C **4910' },
    ],
  },
];
